### ISSUE TITLE
Middleware Usage

### ISSUE THREAD

**Issue by sr2ds** [generationtux/jwt-artisan#10]
Hello Friend,

Sorry for a question so simple, I'm trying to understand how to use your code with the middleware of the lumen, but I do not understand how to work the service provider.
Authentication provider user [api] is not defined.

Can you help me indicating some document or way for me to solve this problem?

Thank you

**Comment by hopewise** [comment]
Hi,
We have wrote our own guard to be used as stateless authentication powered by this repo!
I will add a pull request soon with instructions about how to use the guard and this repo in lumen for backend authentication API 😄  stay tuned!

**Comment by kyleferguson** [comment]
If you would like an implementation idea on how to use Laravel's Guard flow for JWT auth, see https://github.com/generationtux/jwt-artisan/pull/12
