### ISSUE TITLE
How to refresh token?

### ISSUE THREAD

**Issue by kalpitpandit** [generationtux/jwt-artisan#13]
Thanks a ton for creating this package. 

I am using this package in my mobile app to authenticate user. I don't want user to logout after X min and ask them to re-login.

Is there any way that i can refresh the token, if given token is about to expires or expired?

**Comment by ryanscherler** [comment]
I'll second this - is there any methods to invalidate a token?

**Comment by kyleferguson** [comment]
@ryanscherler if you need the ability to invalidate a token, the payload will need to contain some kind of unique identifier, like a nonce, that can be blacklisted to invalidate a token. This package doesn't handle that logic out of the box though.

@kalpitpandit the way we handle refreshes for common patterns such as "remember me" is to issue a new token everytime one is validated. So essentially the user logs in and receives a token. We set the expiration for some amount of time (say 2 days) and every request the user makes will validate the token and then refresh it with a new token and a new timer of 2 days. In this manner, as long as the user is active every 2 days they'll not need to login again, and if they stay inactive for more than 2 days they'll have to login again.
