### ISSUE TITLE
JWT Expired token handler

### ISSUE THREAD

**Issue by ryanscherler** [generationtux/jwt-artisan#15]
I was wondering why the exception handler doesn't account for expired tokens? It seems to cover invalid and missing tokens but for some reason I had to register an additional handler in lumen to catch an instance of Firebase JWT expired token exception and output my own JSON error response. Maybe there is a better way to do this?

**Comment by kyleferguson** [comment]
This is something we should definitely do. Thanks for the heads up. I have a list of improvements that are in progress and I'll make sure this definitely gets taken care of.

**Comment by kyleferguson** [comment]
Contributions are always welcome as well ;)
