### ISSUE TITLE
Error with token creation

### ISSUE THREAD

**Issue by code4hub** [generationtux/jwt-artisan#17]
It's throwing below error,

{"error":true,"code":400,"message":"Argument 2 passed to App\\Http\\Controllers\\LoginController::generateToken() must be an instance of GenTux\\Jwt\\JwtToken, none given, called in \/home\/krds\/Documents\/www\/projects\/krds\/api\/app\/Http\/Controllers\/LoginController.php on line 55 and defined"}

`public function generateToken($id, JwtToken $jwt)
    {
        $payload = ['exp' => time() + 86400, 'sub' => $id]; // expire in 24 hours
        $token = $jwt->createToken($payload); // new instance of JwtToken

        return (string) $token;
    }`

**Comment by Olofguard** [comment]
It sounds like the IOC container isn't resolving an instance of the `JwtToken`. 

Are you sure you've included the service provider?

https://github.com/generationtux/jwt-artisan#setup

**Comment by code4hub** [comment]
Yes. It was not allowing me to call from another controller function. I did instance creation in constructor then it worked. But token validation is working in local system but in production server it's not taking up the header "Authorization: Bearer <token>". so am forced to pass token with the request as "token=<token>"

**Comment by Olofguard** [comment]
Im not entirely sure what you mean by `production server it's not taking up the header "Authorization: Bearer "`. Are you setting the Authorization header on your requests to your service? If the header is set the package should be able to parse it. `sscanf($request->header('Authorization'), 'Bearer %s');`
