### ISSUE TITLE
Problem on token validation

### ISSUE THREAD

**Issue by nmfarshad** [generationtux/jwt-artisan#18]
I am trying to validate the token for test purposes I am using Postman and set the header 
`Authorization : Bearer xxxxxxxxx`

but still I get the error
```
NoTokenException in GetsJwtToken.php line 51:
JWT token is required.
```

**Comment by jlaswell** [comment]
I'm closing this to clean up remaining issues in this repo. Feel free to reopen if you would like help in solving this.
