### ISSUE TITLE
Example Application using plugin

### ISSUE THREAD

**Issue by cyprusglobe** [generationtux/jwt-artisan#2]
Would it be at all possible to do an example laravel 5 starter app with this plugin?

im a little lost on the documentation I'm still new at laravel

**Comment by kyleferguson** [comment]
I'm working on a blog post for getting started w/ JWT auth for Laravel & Lumen using this package. I'll post the link here once it's ready.

**Comment by cyprusglobe** [comment]
@kyleferguson Thanks

**Comment by cyprusglobe** [comment]
@kyleferguson any update on this?

**Comment by kyleferguson** [comment]
Almost finished the article. Going to try and get the blog spun up tonight and posted. Apologize for the delay we've been heads down at work trying to finish up a few things.

**Comment by cyprusglobe** [comment]
@kyleferguson any update on this?

**Comment by mantchido** [comment]
I tried validating a token in my controller and got GetsJwtToken not found error. Please help.

**Comment by kyleferguson** [comment]
@neche are you importing the trait at the top of the class?

```
<?php namespace App\Http\Controllers;

use GenTux\Jwt\GetsJwtToken;

class WhateverController extends Controller {

    use GetsJwtToken;

}
```

**Comment by kyleferguson** [comment]
@cyprusglobe is there a use case specifically I can help you with?

**Comment by mantchido** [comment]
@kyleferguson Yes. I'm using the middleware in the route now. If I don't want the token to expire, how can I go about it?

**Comment by kyleferguson** [comment]
@neche can you create a new issue and describe the workflow you're trying to accomplish, with any examples of what does/doesn't work for you. Would be happy to help.

**Comment by archie20** [comment]
Hi.... Are you still working on the blog?

**Comment by kyleferguson** [comment]
I've started it, work has just been too busy for me lately to get it finished and launched unfortunately :(

Is there something specific I can help you with?

**Comment by mantchido** [comment]
No thank you.
