### ISSUE TITLE
How use Middleware In Laravel  5.6

### ISSUE THREAD

**Issue by kiramishima** [generationtux/jwt-artisan#20]
I detect one bug with Laravel 5.6.* 
You can create  Tokens well and retrieve the payload information with GetJwtToken, but when you implements Middleware validation always throw "Class jwt does not exist" because LaravelServiceProvider cant add the middleware, my solution was: 

Modify app/Http/Kernel.php and add the middleware manually

```

protected $routeMiddleware = [
...
'jwt' => \GenTux\Jwt\Http\JwtMiddleware::class
]

```

Then you can use the middleware in your routes and no more error "Class jwt does not exist"

```
Route::get('/sample', 'SampleController@generate');
Route::get('/sample', 'SampleController@check')->middleware("jwt");
```

or

```
Route::get('/sample', 'SampleController@generate');
Route::middleware(['jwt'])->group(function () {
Route::get('/sample', 'SampleController@check');
});
```

I try to change the signature `LaravelServiceProvider::registerMiddleware` to `LaravelServiceProvider::register` but throws the same error 😢 (I never create Laravel Providers 😂, I dont know if app['router'] exists on Laravel 5.6.* )

**Comment by Olofguard** [comment]
Closing this out as it's stale. Feel free to reopen if you're still having an issue.

**Comment by vadimwe** [comment]
+1 same problem
