### ISSUE TITLE
Blank token

### ISSUE THREAD

**Issue by hugoalvarado** [generationtux/jwt-artisan#4]
Hello,

I am trying to generate a token once a user/pass is validated on my Lumen setup, but the generated token is blank.

I have modified my controller like this:

`
use GenTux\Jwt\JwtToken;
use GenTux\Jwt\Drivers\FirebaseDriver;
use GenTux\Jwt\GetsJwtToken;

class LoginController extends Controller
{
    use GetsJwtToken;
...

```
public function login(Request $request,JwtToken $jwt)
{
```

...
            $payload = ['exp' => time() + 7200]; // expire in 2 hours
            //$jwt = new JwtToken(new FirebaseDriver());
            $token = $jwt->createToken($payload); // new instance of JwtToken

```
        return response()->json(['token' => $token]);
```

}
`

I also tried to create the $jwt object directly but that did not work either. Then env variables are setup as well as the app.php registration. 
Why is the token blank? On your example the JwtToken $jwt is passed to the controller, can you explain where the token is set? Thank you.

**Comment by kyleferguson** [comment]
The `createToken` method returns a new instance of `JwtToken`, with the actual token set on that new object. To get the string value of the token you can either call the `token()` method after creating:

```
// $token as string
$token = $jwtToken->createToken($payload)->token();
```

or you can type hint to a string in your response, which will output the token for response as well

```
$token = $jwtToken->createToken($payload);
return response()->json(['token' => (string) $token]);
```

**Comment by kyleferguson** [comment]
Created a new release `0.1.7` with serialization bugfix that will allow your first implementation to work correctly. See the PR referenced above.

**Comment by hugoalvarado** [comment]
Hi,

I see $token = $jwt->createToken creates the token, but where is the the $jwt object created? I see it as a parameter, is it passed internally by Lumen?

Cool! I will try that. Thanks for the very quick response and fix!

**Comment by hugoalvarado** [comment]
Fix looks goo! I have a token now :)
