### ISSUE TITLE
Jwt invalidate 

### ISSUE THREAD

**Issue by ghost** [generationtux/jwt-artisan#8]
Is there any way to invalidate  the JWT token?

**Comment by kyleferguson** [comment]
Do you mean invalidate one specific token for some reason? Could you provide a use case?

**Comment by ghost** [comment]
When the user logout from the device I need to invalidate the token.

**Comment by kyleferguson** [comment]
Tokens expire based on the `ext` value in the payload, so simply deleting the token from the client (in the session, or local storage, etc.) is usually fine.

**Comment by hartjo** [comment]
we need this invalidate feature for jwt auth for some reason can you implement this? thanks
